<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Status' => '',
    'Add New Document' => '',
    'Affiliated Institution' => '',
    'Are you sure you want to delete this document?' => '',
    'Are you sure you want to delete this item?' => '@@@@',
    'Authentication  ID' => '',
    'Change Password' => '',
    'Comments' => '',
    'Create' => '',
    'Create User Profile' => '',
    'Create User Uploads' => '@@@@',
    'Created' => '',
    'Date Registered' => '',
    'Date Updated' => '',
    'Date Uploaded' => '',
    'Delete' => '@@@@',
    'Delete Document' => '',
    'Document Link' => '',
    'Document Path' => '',
    'Email Address' => '',
    'File Deleted' => '',
    'File Name' => '',
    'Institution  ID' => '',
    'Institution Name' => '',
    'Last Updated' => '',
    'My Documents' => '',
    'My Profile' => '',
    'My Uploads' => '',
    'Other Names' => '',
    'Owner Names' => '',
    'Password' => '',
    'Password Hash' => '@@@@',
    'Password Reset Token' => '',
    'Phone Number' => '',
    'Public Documents' => '',
    'Publicly Available' => '',
    'Register' => '',
    'Repeat Password' => '',
    'Reset' => '',
    'Save Details' => '',
    'Search' => '',
    'Surname' => '',
    'Update' => '',
    'Update Details' => '',
    'Update Document' => '',
    'Update Profile' => '',
    'Update {modelClass}: ' => '',
    'Updated' => '',
    'Upload  ID' => '@@@@',
    'Upload Documents' => '',
    'Upload ID' => '',
    'User  ID' => '',
    'User ID' => '',
    'User Profiles' => '',
    'User Uploads' => '',
    'Username' => '',
    'Welcome' => '',
    'Welcome!' => '',
];
