<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Status' => 'Statut du compte',
    'Are you sure you want to delete this item?' => 'Êtes-vous sûr de bien vouloir supprimer cet élément?',
    'Authentication  ID' => 'ID d\'authentification',
    'Change Password' => "Changer le mot de passe",
    'Comments' => 'Commentaires',
    'Create' => 'Créer',
    'Create User Profile' => 'Créer un profil utilisateur',
    'Create User Uploads' => 'Créer des téléchargements utilisateur',
    'Created' => 'Créé',
    'Date Registered' => '',
    'Date Updated' => 'Date d\'inscription',
    'Date Uploaded' => 'Date de mise à jour',
    'Delete' => 'Date de téléchargement',
    'Document Path' => 'Effacer',
    'Email Address' => 'Chemin du document',
    'File Deleted' => 'Adresse e-mail',
    'Last Updated' => 'Fichier supprimé',
    'Other Names' => 'Dernière mise à jour',
    'Password' => 'Autres noms',
    'Password Hash' => 'Mot de passe',
    'Phone Number' => 'Mot de passe Hash',
    'Publicly Available' => 'Numéro de téléphone',
    'Register' => 'Disponible publiquement',
    'Repeat Password' => 'Registre',
    'Reset' => 'Répéter le mot de passe',
    'Search' => 'Réinitialiser',
    'Surname' => 'Chercher',
    'Update' => 'Nom de famille',
    'Update {modelClass}: ' => '',
    'Updated' => '',
    'Upload  ID' => '',
    'User  ID' => '',
    'User Profiles' => '',
    'User Uploads' => '',
    'Username' => '',
];